nitrogen8mp-smarc-mender and nitrogen8mp-som-mender: intial addition
Create two new machines to support mender integration on Nitrogen8M Plus
SMARC.

Need to create two new machines because on Nitrogen8M Plus SOM the
MENDER_STORAGE_DEVICE is "/dev/mmcblk2", where on Nitrogen8M Plus SMARC
it is "/dev/mmcblk0" (default in mender).

Mender only supports one MENDER_STORAGE_DEVICE per machine and the
"imx8mp_nitrogen_smarc_2gr0_defconfig" (Nitrogen8M Plus SMARC)
UBOOT_CONFIG has "CONFIG_SYS_MMC_ENV_DEV" set to "0", while the
Nitrogen8M Plus SOM defconfigs (nirogen8mp_2g_defconfig, etc,) has
"CONFIG_SYS_MMC_ENV_DEV" set to "2".

This results in an error when using the current nitrogen8mp machine:

ERROR: u-boot-boundary-v2022.04+gitAUTOINC+e5db2035c7-r0 do_configure:
U-Boot configuration  nitrogen8mp_2g_defconfig
nitrogen8mp_2gr0_defconfig nitrogen8mp_4g_defconfig
nitrogen8mp_8g_defconfig imx8mp_nitrogen_smarc_2gr0_defconfig has
setting:
CONFIG_SYS_MMC_ENV_DEV=0
but Mender expects:
CONFIG_SYS_MMC_ENV_DEV=2

Therefore, we cannot use just the one nitrogen8mp machine to support
both Nitrogen8M Plus SMARC and Nitrogen8M Plus SMARC mender BSPs.

Signed-off-by: Chris Dimich <chris.dimich@boundarydevices.com>